/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_GLContext */

#ifndef _Included_org_lwjgl_opengl_GLContext
#define _Included_org_lwjgl_opengl_GLContext
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: current_capabilities */
/* Inaccessible static: fast_path_cache */
/* Inaccessible static: thread_cache_entries */
/* Inaccessible static: capability_cache */
/* Inaccessible static: gl_ref_count */
/* Inaccessible static: did_auto_load */
/*
 * Class:     org_lwjgl_opengl_GLContext
 * Method:    getFunctionAddress
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_opengl_GLContext_getFunctionAddress
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lwjgl_opengl_GLContext
 * Method:    nLoadOpenGLLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GLContext_nLoadOpenGLLibrary
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GLContext
 * Method:    nUnloadOpenGLLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GLContext_nUnloadOpenGLLibrary
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_GLContext
 * Method:    resetNativeStubs
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_GLContext_resetNativeStubs
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
