/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_input_Mouse */

#ifndef _Included_org_lwjgl_input_Mouse
#define _Included_org_lwjgl_input_Mouse
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_input_Mouse_EVENT_SIZE
#define org_lwjgl_input_Mouse_EVENT_SIZE 22L
/* Inaccessible static: created */
/* Inaccessible static: buttons */
/* Inaccessible static: x */
/* Inaccessible static: y */
/* Inaccessible static: coord_buffer */
/* Inaccessible static: dx */
/* Inaccessible static: dy */
/* Inaccessible static: dwheel */
/* Inaccessible static: buttonCount */
/* Inaccessible static: hasWheel */
/* Inaccessible static: currentCursor */
/* Inaccessible static: buttonName */
/* Inaccessible static: buttonMap */
/* Inaccessible static: initialized */
/* Inaccessible static: readBuffer */
/* Inaccessible static: eventButton */
/* Inaccessible static: eventState */
/* Inaccessible static: event_dx */
/* Inaccessible static: event_dy */
/* Inaccessible static: event_dwheel */
/* Inaccessible static: event_x */
/* Inaccessible static: event_y */
/* Inaccessible static: event_nanos */
/* Inaccessible static: grab_x */
/* Inaccessible static: grab_y */
#undef org_lwjgl_input_Mouse_BUFFER_SIZE
#define org_lwjgl_input_Mouse_BUFFER_SIZE 50L
/* Inaccessible static: isGrabbed */
/* Inaccessible static: implementation */
/* Inaccessible static: emulateCursorAnimation */
/* Inaccessible static: allowNegativeMouseCoords */
#ifdef __cplusplus
}
#endif
#endif
